FROM php:8.1-cli-alpine

RUN apk update \
    && apk add --no-cache curl g++ make autoconf bash

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./php-cli/configurations/* /usr/local/etc/php/conf.d/