version: '3.8'

services:
  minimalism-service-discord:
    container_name: minimalism-service-discord
    image: carlonicora/minimalism-service-discord:1.0
    build:
      context: .
      dockerfile: ./php-cli/Dockerfile
    working_dir: /app
    volumes:
      - ../:/app
    tty: true
    stdin_open: true
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora